# Agent 
SELECT DISTINCT ?Agent_url ?hasRegisteredOrganization_url ?reportsTo_url ?headOf_url ?hasMembership_url ?memberOf_url ?holds_url WHERE {
  ?Agent_url a <http://purl.org/dc/terms/Agent> .
  OPTIONAL { ?Agent_url <http://www.w3.org/ns/regorg#hasRegisteredOrganization> ?hasRegisteredOrganization_url . }
  OPTIONAL { ?Agent_url <http://www.w3.org/ns/org#reportsTo> ?reportsTo_url . }
  OPTIONAL { ?Agent_url <http://www.w3.org/ns/org#headOf> ?headOf_url . }
  OPTIONAL { ?Agent_url <http://www.w3.org/ns/org#hasMembership> ?hasMembership_url . }
  OPTIONAL { ?Agent_url <http://www.w3.org/ns/org#memberOf> ?memberOf_url . }
  OPTIONAL { ?Agent_url <http://www.w3.org/ns/org#holds> ?holds_url . }
}
