# Join Organization → classification → Geslacht
SELECT DISTINCT ?Organization_url ?Geslacht_url WHERE {
  ?Organization_url a <http://www.w3.org/ns/org#Organization> .
  ?Geslacht_url a <http://www.w3.org/2004/02/skos/core#Concept> .
  ?Organization_url <http://www.w3.org/ns/org#classification> ?Geslacht_url .
}
